Fix #373
lunarmodules/luasocket pull request #374
Opened 2022-04-01 20:19 UTC by C3pa

Adds and EmmyLua annotation to skip diagnostics on the next line. Here is some more [info](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#diagnostic).

2022-04-01 21:36 UTC, alerque requested changes
Lets follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification for commit messages. Your PR and issue have relevant issue but the commit message will not be very informative in a changelog later. Lets try something like:

```
chore: Annotate lowercase global to avoid EmmyLua warning
```

2022-04-02 20:22 UTC, alerque approved these changes

2022-04-15 09:46 UTC, Tieske commented
I do not like this. LuaSocket should not be changed because downstream projects have (extremely) arbitrary linting rules. In this case for globals to be required in allcaps.

My 2cts.

2022-04-15 10:50 UTC, C3pa commented
Well, it's not a problem for me. I can easily apply a patch on top. I just offered this to see if there is some interest.

2022-04-15 11:00 UTC, alerque commented
@Tieske You do realize we already have a similar lint ignore rule here and a couple other places in our source to accommodate `luacheck`, right? The stunt we're pulling on that line of code is just a bit unconventional and understandable makes linter(s) unhappy. The *reason* EmmyLua* is unhappy is (IMO) sillier than the reason luacheck is unhappy and I would much rather see a config file in the project root to disable this silly rule for the whole project, but as far as I know that isn't supported and one rule to accommodate a lot of people and potential contributors that happen to be using VScode doesn't seem like too much of a burden to me.

2022-04-15 12:07 UTC, Tieske commented
It's a slippery slope imo. The luacheck exceptions are here because this project actively uses it to check against its own guidelines for proper code.

I agree it's not too much hassle, but it's just not a responsibility of this project. If anything then EmmyLua should exclude those files from their linter. And even more so because they use a different one from LuaCheck. Anyone casually looking at the LuaSocket code will be baffled by those lines.

Just my 2cts, don't want to block this solely on my opinion though.

2022-04-21 17:05 UTC, C3pa commented
Since there is no interest in this, I'll close this and apply the patch downstream.

2022-04-21 17:05 UTC, closed without merging